[workspace]
channels = ["conda-forge"]
name = "stress_test"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
git_add = "git add --all"
git_commit = {cmd = "git commit -m {{message}}", args = ["message"]}
git_push = "git push"
git_sync = { depends-on = ["git_add", { task = "git_commit", args = ["\"{{message}}\""] }, "git_push"], args = ["message"] }

[activation.env]
OPENROUTER_API_KEY=""

[dependencies]
python = ">=3.14.4,<3.15"
ipykernel = ">=7.2.0,<8"

[pypi-dependencies]
pandas = ">=3.0.2, <4"
datasets = ">=4.8.4, <5"
openai = ">=2.33.0, <3"
