[workspace]
channels = ["conda-forge"]
name = "stress_test"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.4,<3.15"
ipykernel = ">=7.2.0,<8"

[pypi-dependencies]
pandas = ">=3.0.2, <4"
datasets = ">=4.8.4, <5"
